export interface GameState {
  coins: number;
  wheatSeeds: number;
  wheat: number;
  tomatoSeeds: number;
  tomatoes: number;
  crops: import("./Crop").Crop[];
  milk: number;
  pork: number;
  butter: number;
  cheese: number;
  ham: number;
  sausage: number;
  bacon: number;
  cowProductions: import("./Cow").CowProduction[];
  pigProductions: import("./Pig").PigProduction[];
  milkFactoryProductions: import("./MilkFactory").MilkFactoryProduction[];
  porkFactoryProductions: import("./PorkFactory").PorkFactoryProduction[];
  villageLevel: number;
  residents: import("./Resident").Resident[];
  buildings: import("./Building").BuildingInstance[];
  unlockedCountries: string[];
  unlockedBuildings: string[];
  activeResidentRequest: import("./ResidentRequest").ActiveResidentRequest | null;
  nextResidentRequestAt: number;
  lastResidentRequestDefinitionId?: string;
  residentRequestDayKey: string;
  residentRequestsStartedToday: number;
  lastSavedAt: number;
}
