export interface GameState {
  coins: number;
  wheatSeeds: number;
  tomatoSeeds: number;
  riceSeeds: number;
  crops: import("./Crop").Crop[];
  inventory: import("./Inventory").InventoryState;
  miningInventory: import("./Mining").MiningInventory;
  caveMining: import("./Mining").CaveMiningState;
  hasFishingRod: boolean;
  currentMap: import("./Map").MapId;
  cowProductions: import("./Cow").CowProduction[];
  pigProductions: import("./Pig").PigProduction[];
  chickenProductions: import("./Chicken").ChickenProduction[];
  milkFactoryProductions: import("./MilkFactory").MilkFactoryProduction[];
  porkFactoryProductions: import("./PorkFactory").PorkFactoryProduction[];
  wheatFactoryProductions: import("./WheatFactory").WheatFactoryProduction[];
  villageLevel: number;
  residents: import("./Resident").Resident[];
  buildings: import("./Building").BuildingInstance[];
  buildingUpgrades: import("./BuildingUpgrade").BuildingUpgradeState;
  encyclopediaCollectedIds: string[];
  unlockedCountries: string[];
  unlockedBuildings: string[];
  activeResidentRequest: import("./ResidentRequest").ActiveResidentRequest | null;
  nextResidentRequestAt: number;
  lastResidentRequestDefinitionId?: string;
  residentRequestDayKey: string;
  residentRequestsStartedToday: number;
  marketOrders: import("./MarketOrder").MarketOrder[];
  marketOrderSequence: number;
  lastSavedAt: number;
}
