import { createInitialResident } from "../systems/ResidentSystem";
import {
  INITIAL_TOMATO_SEEDS,
  INITIAL_WHEAT_SEEDS,
  INITIAL_RICE_SEEDS,
  RESIDENT_REQUEST_INITIAL_DELAY_MS,
} from "../constants/gameConstants";
import type { GameState } from "../types/Village";
import { getLocalDateKey } from "../../utils/date";
import { createInitialFishInventory } from "../data/fish";
import { syncEncyclopediaCollection } from "../systems/EncyclopediaSystem";

export function createInitialGameState(now = Date.now()): GameState {
  return syncEncyclopediaCollection({
    coins: 100,
    wheatSeeds: INITIAL_WHEAT_SEEDS,
    wheat: 0,
    tomatoSeeds: INITIAL_TOMATO_SEEDS,
    tomatoes: 0,
    riceSeeds: INITIAL_RICE_SEEDS,
    rice: 0,
    crops: [],
    eggs: 0,
    milk: 0,
    pork: 0,
    wheatFlour: 0,
    butter: 0,
    cheese: 0,
    ham: 0,
    sausage: 0,
    bacon: 0,
    pizzas: 0,
    bread: 0,
    hotDogs: 0,
    croissants: 0,
    hamSandwiches: 0,
    onigiri: 0,
    omurice: 0,
    fishInventory: createInitialFishInventory(),
    currentMap: "village",
    cowProductions: [],
    pigProductions: [],
    chickenProductions: [],
    milkFactoryProductions: [],
    porkFactoryProductions: [],
    wheatFactoryProductions: [],
    villageLevel: 1,
    residents: [createInitialResident("poland", { x: 6.5, z: 5.5 })],
    buildings: [
      { id: "house-1", buildingId: "house", gridX: 5, gridY: 5 },
      { id: "fountain-1", buildingId: "fountain", gridX: 9, gridY: 9 },
      { id: "tree-1", buildingId: "tree", gridX: 3, gridY: 3 },
      { id: "tree-2", buildingId: "tree", gridX: 16, gridY: 4 },
    ],
    encyclopediaCollectedIds: [],
    unlockedCountries: ["poland"],
    unlockedBuildings: [
      "field",
      "fence",
      "road",
      "milk-factory",
      "pork-factory",
      "wheat-factory",
      "bakery",
      "cow",
      "pig",
      "chicken",
      "tree",
      "flower",
    ],
    activeResidentRequest: null,
    nextResidentRequestAt: now + RESIDENT_REQUEST_INITIAL_DELAY_MS,
    residentRequestDayKey: getLocalDateKey(now),
    residentRequestsStartedToday: 0,
    lastSavedAt: now,
  });
}
